//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Text;
using ChessGame;

public class King : Piece
{
    public King(PieceColor pieceColor) : base(pieceColor)
    {
        MoveRule = MoveRules.King;
    }
    
    public override string ToString()
    { 
            return "K";   
    }


}

