//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ChessGame;

public class Knight : Piece
{
    public Knight(PieceColor pieceColor) : base(pieceColor)
    {
        MoveRule = MoveRules.Knight;
    }

    public override string ToString()
    {
        return "S";
    }

}